---
- hosts: all
  become: true
  tasks:

  - name: Install Python3-apt
    apt:
      name:
        - python3-apt

  
  - name: Add Docker DPG Key
    apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

  - name: Add Docker Repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu impish stable
      state: present



  - name: Install Docker Dependecy
    apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - docker-ce
        - docker-compose


