---
- hosts: all
  become: true
  tasks:
  
  - community.general.ufw:
      state: enabled

  - name: Set loggin
    community.general.ufw:
      logging: 'on'

  - community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp

  - community.general.ufw:
      rule: allow
      port: 22
      proto: tcp


