---
- hosts: all
  become: true
  tasks:
  
  - name: Enable UFW
    community.general.ufw:
      state: enabled

  - name: Set loggin
    community.general.ufw:
      logging: 'on'

  - name: Allow SSH
    community.general.ufw:
      rule: allow
      port: 22
      proto: tcp

  - name: Allow Plex
    community.general.ufw:
      rule: allow
      port: 32400
      proto: tcp

  - name: Reload UFW
    community.general.ufw:
      state: reloaded
