---
- hosts: all
  become: true
  tasks:
  
  - name: Create vm_storage Directory
    file:
      path: /mnt/photos
      state: directory

  - name: Mount NFS Photo-Storage Drive
    ansible.posix.mount:
      src: 10.50.30.3:/mnt/Data/photos
      path: /mnt/photos
      opts: rw,sync,hard,intr
      fstype: nfs
      state: mounted
