---
- hosts: all
  become: true
  tasks:
  
  - name: Create Plex Directory
    file:
      path: /mnt/plex
      state: directory

  - name: Mount NFS Photo-Storage Drive
    ansible.posix.mount:
      src: 10.50.30.3:/mnt/Data/plex
      path: /mnt/plex
      opts: rw,sync,hard,intr
      fstype: nfs
      state: mounted
