 ---
- hosts: all
  become: true
  tasks:
  
  - name: Mount NTFS VM-Storage Drive
    ansible.posix.mount:
      src: 10.50.30.3:/mnt/Data/vm-storage
      path: /mnt/vm_storage
      opts: rw,sync,hard,intr
      state: mounted
      fstype: nfs


  - name: Create vm_storage Directory
    file:
      path: /mnt/vm_storage
      state: directory


