---
 - hosts: all
   become: true
   tasks:

     - name: Add Apt Cache Proxy to Ubuntu/Debian
       ansible.builtin.lineinfile:
         path: /etc/apt/apt.conf.d/02proxy
         line: Acquire::http { Proxy "http://10.50.30.2:3142"; };
         create: yes
       when: (ansible_distribution == "Debian") or (ansible_distribution == "Ubuntu")


     - name: Add Apt Cache Proxy to DNF
       ansible.builtin.lineinfile:
         path: /etc/dnf/dnf.conf
         line: proxy=http://10.50.30.2:3142
       when: (ansible_distribution == "Fedora")

