---
- hosts: all
  become: true
  tasks:
  
  - name: Add Apt Cache Proxy to Ubuntu/Debian
    ansible.builtin.lineinfile:
      path: /etc/apt/apt.conf.d/02proxy
      line: Acquire::http { Proxy "http://10.50.30.2:3142"; };
      create: yes
    when: (ansible_distribution == "Debian") or (ansible_distribution == "Ubuntu")


  - name: Add Apt Cache Proxy to DNF
    ansible.builtin.lineinfile:
      path: /etc/dnf/dnf.conf
      line: proxy=http://10.50.30.2:3142
    when: (ansible_distribution == "Fedora")


  - name: Add SSH Keys
    authorized_key:
      user: chris
      state: present
      key: '{{ item }}'
    with_file:
      - ~/Ansible/ssh_keys/chris-macbook.pub
      - ~/Ansible/ssh_keys/manjaro.desktop.pub

  - name: Remove Fedora SSh Key
    authorized_key:
      user: chris
      state: remove
      key: '{{ item }}'
    with_file:
      - ~/Ansible/ssh_keys/fedora_desktop.pub


  - name: Update Repository Index
    apt: 
      update_cache: yes
  
  - name: Install Packages
    apt:
      name:
        - ufw
        - net-tools
        - nfs-common

  - name: Enable UFW
    community.general.ufw:
      state: enabled

  - name: Set Loggin
    community.general.ufw:
      logging: 'on'

  - name: Allow SSH
    community.general.ufw:
      rule: allow
      port: 22
      proto: tcp

  - name: reload UFW
    community.general.ufw:
      state: reloaded
