---
- hosts: all
  become: true
  tasks:
  
  - name: Update Repository Index
    apt: 
      update_cache: yes
  
  - name: Install Packages
    apt:
      name:
        - ufw
        - net-tools
        - nfs-common

  - name: Enable UFW
    community.general.ufw:
      state: enabled

  - name: Set Loggin
    community.general.ufw:
      logging: 'on'

  - name: Allow SSH
    community.general.ufw:
      rule: allow
      port: 22
      proto: tcp

  - name: reload UFW
    community.general.ufw:
      state: reloaded
